var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.polyfill("Object.entries",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push([d,a[d]]);return b}},"es8","es3");(function(a){switch(a.hostname){case "localhost":break;default:"https:"!==a.protocol&&(a.href="https://"+a.host+a.pathname+a.search)}})(window.location);window.localizedRoutes=["illustrations","character-design","animals","black-and-white","contact"];
(function(a){if(a.search){try{var b=Object.fromEntries(a.search.slice(1).split("&").map(function(a){return a.split("=")}))}catch(c){a.href=a.protocol+"//"+a.host+a.pathname+"?page=illustrations"}b.page&&window.localizedRoutes.includes(b.page)||(b.page={highlights:"illustrations"}[b.page]||"illustrations",b=Object.entries(b).map(function(a){var b=$jscomp.makeIterator(a);a=b.next().value;return(b=b.next().value)?a+"="+b:""}).join("&"),a.href=a.protocol+"//"+a.host+a.pathname+(b?"?"+b:""))}})(window.location);
var Aggregate=function(a){this.nodes=[].concat($jscomp.arrayFromIterable(a))};Aggregate.prototype.click=function(a){this.nodes.forEach(function(b){b.addEventListener("click",function(){a(b)})})};Aggregate.prototype.addClass=function(a){this.nodes.forEach(function(b){b.classList.add(a)})};Aggregate.prototype.removeClass=function(a){this.nodes.forEach(function(b){b.classList.remove(a)})};
Aggregate.prototype.toggleClass=function(a){this.nodes.forEach(function(b){b.classList.contains(a)?b.classList.remove(a):b.classList.add(a)})};window.$$=function(a){return new Aggregate(document.querySelectorAll(a))};
(function(a){if(!a.SITE){var b={fetchJSON:function(b){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];console.log("FETCHING JSON DATA");return a.fetch.apply(a,$jscomp.arrayFromIterable(c)).then(function(a){return a.json()})},fetchTEXT:function(b){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];console.log("FETCHING HTML",c);return a.fetch.apply(a,$jscomp.arrayFromIterable(c)).then(function(a){return a.text()})},paths:{images:"./assets/images/",html:"./assets/html/"},nav:{}};
b.nav.getActivePage=function(){if(a.location.search)return(new URL(a.location.href)).searchParams.get("page");b.nav.goto("illustrations",!0)};b.nav.goto=function(c,d){if(c){if(void 0===d?0:d)a.location="/?page="+c;b.nav.routes.includes(c)?(a.history.pushState({page:c},c,"/?page="+c),render(a.SITE.assets)):b.nav.externalRoutes[c]?(a.open(b.nav.externalRoutes[c]),gtag&&gtag("config","UA-136826563-1",{page_title:c,page_path:"/:goto:/"+c})):(gtag&&gtag("config","UA-136826563-1",{page_title:"UNKNOWN_PAGE:"+
c,page_path:"/:goto:/"+c}),b.nav.goto("illustrations"))}};b.nav.routes=a.localizedRoutes;b.nav.externalRoutes={etsy:"https://www.etsy.com/shop/McKenzieRoseDesign",instagram:"https://www.instagram.com/mckenzierose_studio/"};a.addEventListener("popstate",function(b){b.state.page&&render(a.SITE.assets)});b.cache={};b.clearCache=function(){b.cache={}};b.trackMediaClick=function(a){a=a.name;gtag&&gtag("config","UA-136826563-1",{page_title:a,page_path:"/:goto:/"+a+"?via=contact"})};a.SITE=b}})(window);
function selectTab(a){$$("nav li").removeClass("active");$$("nav li[name="+a+"]").addClass("active");a=document.querySelector("nav li[name="+a+"]").innerText.trim();document.title="McKenzie Rose Studio | "+a}function conditionalRender(a,b){SITE.cache[b]?document.querySelector("main").innerHTML=SITE.cache[b]:SITE.cache[b]=renderImages(a[b],b)}
function conditionalStaticPageRender(a){SITE.cache[a]?document.querySelector("main").innerHTML=SITE.cache[a]:SITE.fetchTEXT(""+SITE.paths.html+a+".html").then(function(b){return SITE.cache[a]=b}).then(renderStaticPage)}function render(a){var b=getPage();selectTab(b);switch(b){case "contact":case "character-design":conditionalStaticPageRender(b);break;default:conditionalRender(a,b)}gtag&&gtag("config","UA-136826563-1",{page_title:b,page_path:location.pathname+location.search})}
function getPage(){return SITE.nav.getActivePage()}function renderStaticPage(a){document.querySelector("main").innerHTML=a}var humanReadable=function(a){return a.replace(/-/g," ").split(" ").map(function(a){return a[0].toUpperCase()+a.substr(1)}).join(" ")};
function renderImages(a,b,c){c=void 0===c?"main":c;console.log("renderImages: calculating renderables for '"+b+"'");var d='<div class="masonry">';a.forEach(function(a){var c=$jscomp.makeIterator(a.split(".")).next().value;c=humanReadable(window.getPage())+": "+humanReadable(c);d+='<div class="brick"><img alt="'+c+'" src="'+SITE.assets.meta.minPaths[b]+"/"+a+'" tabindex="0"></div>'});d+="</div>";return document.querySelector(c).innerHTML=d}function placeIllustrations(){}
function getNumPartitions(a){return 4};